server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  application:
    name: math-system
  datasource:
    url: jdbc:postgresql://localhost:5433/math-system-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
api:
  security:
    jwt:
      secret-key: "4d6251655468576d5a7134743777217a25432a462d4a614e645267556a586e32"
      access-token-expiration: 3600000
      refresh-token-expiration: 86400000
  cors:
    allowed-origins: "http://192.168.230.232:3000"